ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS input_tokens INTEGER;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS output_tokens INTEGER;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS cost_usd NUMERIC(10, 6);
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS usage_detail JSONB;