from app.graph import Finding

MARKER = "<!-- multi-agent-pr-reviewer -->"

SEVERITY_EMOJI = {"high": "🔴", "medium": "🟡", "low": "🔵"}


def render_comment(summary: str, high: list[Finding], low_count: int) -> str:
    lines = [MARKER, "## 🤖 Automated review", "", summary, ""]

    if high:
        lines.append(f"### Findings ({len(high)})")
        for f in high:
            loc = f"`{f.file}`" + (f":{f.line}" if f.line else "")
            emoji = SEVERITY_EMOJI.get(f.severity, "•")
            lines.append(
                f"- {emoji} **{f.category}** · {loc} "
                f"_(confidence {f.confidence:.2f})_  \n  {f.message}"
            )
        lines.append("")
    else:
        lines.append("No high-confidence issues found. ✅\n")

    if low_count:
        lines.append(
            f"_{low_count} lower-confidence finding(s) were recorded but not posted._"
        )

    lines.append("\n<sub>Generated by multi-agent-pr-reviewer.</sub>")
    return "\n".join(lines)